/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  serverExternalPackages: ['mongoose'],
  images: {
    formats: ['image/avif', 'image/webp'],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'cleanz24.com',
      },
    ],
  },
  async redirects() {
    return [
      { source: '/laundry', destination: '/best-laundry-drycleaning', permanent: true },
      { source: '/laundry/franchise', destination: '/franchise-opportunities-in-india', permanent: true },
      { source: '/laundry/franchise/:path*', destination: '/best-laundry-drycleaning/franchise-opportunities/:path*', permanent: true },
      { source: '/laundry/:path*', destination: '/best-laundry-drycleaning/:path*', permanent: true },
      { source: '/best-laundry-dryclean', destination: '/best-laundry-drycleaning', permanent: true },
      { source: '/best-laundry-dryclean/:path*', destination: '/best-laundry-drycleaning/:path*', permanent: true },
      { source: '/stores', destination: '/best-laundry-drycleaning/stores', permanent: true },
      { source: '/franchise', destination: '/franchise-opportunities-in-india', permanent: true },
      { source: '/franchise-opportunities', destination: '/franchise-opportunities-in-india', permanent: true },
      { source: '/best-laundry-franchise', destination: '/franchise-opportunities-in-india', permanent: true },
      { source: '/laundry-franchise', destination: '/franchise-opportunities-in-india', permanent: true },
      { source: '/best-laundry-drycleaning/franchise-opportunities', destination: '/franchise-opportunities-in-india', permanent: true },
      { source: '/car-spa-franchise', destination: '/car-spa/franchise', permanent: true },
      { source: '/shoe-cleaning', destination: '/best-laundry-drycleaning/services/shoe-handbag-spa', permanent: true },
      { source: '/shoe-spa', destination: '/best-laundry-drycleaning/services/shoe-handbag-spa', permanent: true },
      { source: '/sneaker-cleaning', destination: '/best-laundry-drycleaning/services/shoe-handbag-spa', permanent: true },
      { source: '/bag-cleaning', destination: '/best-laundry-drycleaning/services/shoe-handbag-spa', permanent: true },
      { source: '/leather-care', destination: '/best-laundry-drycleaning/services/shoe-handbag-spa', permanent: true },
      { source: '/leather-cleaning', destination: '/best-laundry-drycleaning/services/shoe-handbag-spa', permanent: true },
      { source: '/steam-ironing', destination: '/best-laundry-drycleaning/services/steam-ironing', permanent: true },
      { source: '/steam-press', destination: '/best-laundry-drycleaning/services/steam-ironing', permanent: true },
      { source: '/ironing', destination: '/best-laundry-drycleaning/services/steam-ironing', permanent: true },
      { source: '/wash-and-iron', destination: '/best-laundry-drycleaning/services/steam-ironing', permanent: true },
      { source: '/dry-cleaning', destination: '/best-laundry-drycleaning/services/eco-friendly-dry-cleaning', permanent: true },
      { source: '/drycleaning', destination: '/best-laundry-drycleaning/services/eco-friendly-dry-cleaning', permanent: true },
      { source: '/dry-cleaner', destination: '/best-laundry-drycleaning/services/eco-friendly-dry-cleaning', permanent: true },
      { source: '/suit-cleaning', destination: '/best-laundry-drycleaning/services/eco-friendly-dry-cleaning', permanent: true },
      { source: '/saree-cleaning', destination: '/best-laundry-drycleaning/services/eco-friendly-dry-cleaning', permanent: true },
      { source: '/carpet-cleaning', destination: '/best-laundry-drycleaning/services/home-furnishing-cleaning', permanent: true },
      { source: '/curtain-cleaning', destination: '/best-laundry-drycleaning/services/home-furnishing-cleaning', permanent: true },
      { source: '/sofa-cleaning', destination: '/best-laundry-drycleaning/services/home-furnishing-cleaning', permanent: true },
      { source: '/blanket-cleaning', destination: '/best-laundry-drycleaning/services/home-furnishing-cleaning', permanent: true },
      { source: '/wash-and-fold', destination: '/best-laundry-drycleaning/services/premium-laundry', permanent: true },
      { source: '/commercial-cleaning', destination: '/best-laundry-drycleaning/services/commercial-laundry', permanent: true },
      { source: '/contact-us', destination: '/best-laundry-drycleaning/contact-us', permanent: true },
      { source: '/contact', destination: '/best-laundry-drycleaning/contact-us', permanent: true },
      { source: '/services', destination: '/best-laundry-drycleaning/services', permanent: true },
      { source: '/laundry-services', destination: '/best-laundry-drycleaning/services', permanent: true },
      { source: '/best-laundry-and-dry-cleaning', destination: '/best-laundry-drycleaning/services', permanent: true },
      { source: '/carspa', destination: '/car-spa', permanent: true },
      { source: '/car-spa-services', destination: '/car-spa/services', permanent: true },
      { source: '/car-spa-book', destination: '/car-spa/book', permanent: true },
      { source: '/book', destination: '/car-spa/book', permanent: true },
      { source: '/blog', destination: '/best-laundry-drycleaning/blog', permanent: true },
      { source: '/about', destination: '/best-laundry-drycleaning/services', permanent: true },
      { source: '/about-us', destination: '/best-laundry-drycleaning/services', permanent: true },
      { source: '/privacy-policy', destination: '/best-laundry-drycleaning/privacy-policy', permanent: true },
      { source: '/terms-of-service', destination: '/best-laundry-drycleaning/terms-of-service', permanent: true },
    ];
  },
};

export default nextConfig;
