export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';
export const GOOGLE_SHEETS_SCRIPT_URL = import.meta.env.VITE_GOOGLE_SHEETS_SCRIPT_URL || 'https://script.google.com/macros/s/AKfycbxYT5JK8gK9uCZ9zYehZHcJgALe3-G6vUwbhdfdTR5exAt1qgXfGDgpiEPdaldFSKb7/exec';
export const GOOGLE_SHEETS_FRANCHISE_SCRIPT_URL = import.meta.env.VITE_GOOGLE_SHEETS_FRANCHISE_SCRIPT_URL || 'https://script.google.com/macros/s/AKfycbwlp3Na_Utdtze__h39HnoypjgrFpNFkRnfIhtXs0L8C42Bo8ZQ07w8vWYCR250zZsisg/exec';
export const GOOGLE_SHEETS_FRANCHISE_SCRIPT_URL_2 = import.meta.env.VITE_GOOGLE_SHEETS_FRANCHISE_SCRIPT_URL_2 || '';

// Laundry specific sheets
export const GOOGLE_SHEETS_LAUNDRY_SCRIPT_URL = import.meta.env.VITE_GOOGLE_SHEETS_LAUNDRY_SCRIPT_URL || GOOGLE_SHEETS_SCRIPT_URL;
export const GOOGLE_SHEETS_LAUNDRY_FRANCHISE_SCRIPT_URL = import.meta.env.VITE_GOOGLE_SHEETS_LAUNDRY_FRANCHISE_SCRIPT_URL || GOOGLE_SHEETS_FRANCHISE_SCRIPT_URL;
export const GOOGLE_SHEETS_LAUNDRY_FRANCHISE_SCRIPT_URL_2 = import.meta.env.VITE_GOOGLE_SHEETS_LAUNDRY_FRANCHISE_SCRIPT_URL_2 || GOOGLE_SHEETS_FRANCHISE_SCRIPT_URL_2 || '';

// Car Spa specific sheets
export const GOOGLE_SHEETS_CAR_SPA_SCRIPT_URL = import.meta.env.VITE_GOOGLE_SHEETS_CAR_SPA_SCRIPT_URL || GOOGLE_SHEETS_SCRIPT_URL;
export const GOOGLE_SHEETS_CAR_SPA_FRANCHISE_SCRIPT_URL = import.meta.env.VITE_GOOGLE_SHEETS_CAR_SPA_FRANCHISE_SCRIPT_URL || GOOGLE_SHEETS_FRANCHISE_SCRIPT_URL;
export const GOOGLE_SHEETS_CAR_SPA_FRANCHISE_SCRIPT_URL_2 = import.meta.env.VITE_GOOGLE_SHEETS_CAR_SPA_FRANCHISE_SCRIPT_URL_2 || GOOGLE_SHEETS_FRANCHISE_SCRIPT_URL_2 || '';

// Hiring / Recruitment sheet
export const GOOGLE_SHEETS_HIRING_SCRIPT_URL = import.meta.env.VITE_GOOGLE_SHEETS_HIRING_SCRIPT_URL || 'https://script.google.com/macros/s/AKfycbzQ-wRmCyxX5_-BFrSdNziJkiaI3k6drSCGp77rBwYNzHU4PY44cbSZaMMjWRROen_1/exec';
